### ISSUE TITLE
esp_zb_zcl_set_attribute_val generate Guru Meditation Error 

### ISSUE THREAD

**Issue by luigidoria** [espressif/esp-zigbee-sdk#56]
I'm trying to create an end device sample to send numbers to the coordinator.

The end device successfully joins the Zigbee network but can't send the numbers. When I try to use esp_zb_zcl_set_attribute_val, this error occurs:

```
Guru Meditation Error: Core  0 panic'ed (Load access fault). Exception was unhandled.

Core  0 register dump:
Stack dump detected
MEPC    : 0x4202388e  RA      : 0x42023c50  SP      : 0x4084edc0  GP      : 0x4080c5c0  
0x4202388e: zb_zcl_get_attr_desc_manuf at ??:?

0x42023c50: zb_zcl_get_attr_desc_manuf_a at ??:?

TP      : 0x40843894  T0      : 0x4000af8c  T1      : 0x00000000  T2      : 0x00000000  
0x4000af8c: multi_heap_internal_unlock in ROM

S0/FP   : 0x00000000  S1      : 0x0000ffff  A0      : 0x00000000  A1      : 0x00000000  
A2      : 0x0000ffff  A3      : 0x00000000  A4      : 0x0000ffff  A5      : 0x00000000  
A6      : 0x00000001  A7      : 0x0000000a  S2      : 0x0000fffe  S3      : 0x00000001  
S4      : 0x0000fffe  S5      : 0x00000000  S6      : 0x00000001  S7      : 0x000000ad  
S8      : 0x0000006b  S9      : 0x000000f7  S10     : 0x00000000  S11     : 0x00000000  
T3      : 0x00000000  T4      : 0xfff95560  T5      : 0xad6bf7fe  T6      : 0xfff95560  
MSTATUS : 0x00001881  MTVEC   : 0x40800001  MCAUSE  : 0x00000005  MTVAL   : 0x00000004  
0x40800001: _vector_table at ??:?

MHARTID : 0x00000000  


Backtrace:


0x4202388e in zb_zcl_get_attr_desc_manuf ()
#0  0x4202388e in zb_zcl_get_attr_desc_manuf ()
#1  0x42023c50 in zb_zcl_get_attr_desc_manuf_a ()
Backtrace stopped: frame did not save the PC
ELF file SHA256: c9b5f6db9
```

End device code:

```
static void value_generator(void)
{
    while (1) {
        ESP_LOGI(TAG, "Define the value");
        
        int *msg;
        int value = 55;
        msg = &value;
        ESP_LOGI(TAG,"Value: %d", *msg);

        ESP_LOGI(TAG, "Send the value");
        esp_zb_zcl_status_t status = esp_zb_zcl_set_attribute_val(1, 0xFFFE, ESP_ZB_ZCL_CLUSTER_SERVER_ROLE, 0x00, &msg, true);

                if (status == ESP_ZB_ZCL_STATUS_SUCCESS) {
            ESP_LOGI(TAG, "Mesage send correctly");
        } else {
            ESP_LOGI(TAG, "Mesage send incorrectly");
        }
        ESP_LOGI(TAG, " Begin sleep for 5 seconds");
        sleep(5);
        ESP_LOGI(TAG, "End sleep for 5 seconds");
    }
}

```

Coordinator code:

```
void attr_cb(uint8_t status, uint8_t endpoint, uint16_t cluster_id, uint16_t attr_id, void *new_value)
{
    if (cluster_id == MSG_CLUSTER_ID) {
        uint8_t value = *(uint8_t *)new_value;
        if (attr_id == MSG_ATTR_ID) {
            ESP_LOGI(TAG, "Read %hd", value);
           
        }
    } else {
        /* Implement some actions if needed when other cluster changed */
        ESP_LOGI(TAG, "cluster:0x%x, attribute:0x%x changed ", cluster_id, attr_id);
    }
}

static void esp_zb_task(void *pvParameters)
{
    /* initialize Zigbee stack with Zigbee end-device config */
    esp_zb_cfg_t zb_nwk_cfg = ESP_ZB_ZC_CONFIG();
    esp_zb_init(&zb_nwk_cfg);
   
    int value = 0;

    esp_zb_attribute_list_t *FFFE = esp_zb_zcl_attr_list_create(0xFFFE);
    esp_zb_custom_cluster_add_custom_attr(FFFE, 0x00, 0x23, ESP_ZB_ZCL_ATTR_ACCESS_READ_WRITE,&value);
    
    esp_zb_cluster_list_t *esp_zb_cluster_list = esp_zb_zcl_cluster_list_create();
    esp_zb_cluster_list_add_custom_cluster(esp_zb_cluster_list, FFFE, ESP_ZB_ZCL_CLUSTER_SERVER_ROLE);
    esp_zb_device_add_set_attr_value_cb(attr_cb);
    
    esp_zb_set_primary_network_channel_set(ESP_ZB_PRIMARY_CHANNEL_MASK);
    ESP_ERROR_CHECK(esp_zb_start(false));
    esp_zb_main_loop_iteration();
}

```

**Comment by KMTsvetanov** [comment]
can you provide the code for the end device?
